// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BanRecord is the predicate function for banrecord builders.
type BanRecord func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
