// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.0
// source: login/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason 枚举定义了登录操作中可能出现的错误原因，每个错误原因都关联了一个错误码。
type ErrorReason int32

const (
	// USER_DOES_NOT_EXIST 表示请求的用户账号不存在，对应的 HTTP 状态码为 404 Not Found。
	ErrorReason_USER_DOES_NOT_EXIST ErrorReason = 0
	// INCORRECT_PASSWORD 表示用户输入的密码不正确，对应的 HTTP 状态码为 405 Method Not Allowed。
	ErrorReason_INCORRECT_PASSWORD ErrorReason = 1
	// ACCOUNT_HAS_BEEN_BANNED 表示用户账号已被封禁，无法进行登录操作，对应的 HTTP 状态码为 406 Not Acceptable。
	ErrorReason_ACCOUNT_HAS_BEEN_BANNED ErrorReason = 2
	// LOGIN_ERROR 表示登录过程中出现了未预期的错误，对应的 HTTP 状态码为 407 Proxy Authentication Required。
	ErrorReason_LOGIN_ERROR ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_DOES_NOT_EXIST",
		1: "INCORRECT_PASSWORD",
		2: "ACCOUNT_HAS_BEEN_BANNED",
		3: "LOGIN_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"USER_DOES_NOT_EXIST":     0,
		"INCORRECT_PASSWORD":      1,
		"ACCOUNT_HAS_BEEN_BANNED": 2,
		"LOGIN_ERROR":             3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_login_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_login_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_login_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_login_v1_error_reason_proto protoreflect.FileDescriptor

const file_login_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1blogin/v1/error_reason.proto\x12\x0flayout.login.v1\x1a\x13errors/errors.proto*\x84\x01\n" +
	"\vErrorReason\x12\x1d\n" +
	"\x13USER_DOES_NOT_EXIST\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1c\n" +
	"\x12INCORRECT_PASSWORD\x10\x01\x1a\x04\xa8E\x95\x03\x12!\n" +
	"\x17ACCOUNT_HAS_BEEN_BANNED\x10\x02\x1a\x04\xa8E\x96\x03\x12\x15\n" +
	"\vLOGIN_ERROR\x10\x03\x1a\x04\xa8E\x97\x03Bm\n" +
	"+github.com.go-lynx.lynx-layout.api.login.v1B\fLoginProtoV1P\x01Z.github.com/go-lynx/lynx-layout/api/login/v1;v1b\x06proto3"

var (
	file_login_v1_error_reason_proto_rawDescOnce sync.Once
	file_login_v1_error_reason_proto_rawDescData []byte
)

func file_login_v1_error_reason_proto_rawDescGZIP() []byte {
	file_login_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_login_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_v1_error_reason_proto_rawDesc), len(file_login_v1_error_reason_proto_rawDesc)))
	})
	return file_login_v1_error_reason_proto_rawDescData
}

var file_login_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_login_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: layout.login.v1.ErrorReason
}
var file_login_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_v1_error_reason_proto_init() }
func file_login_v1_error_reason_proto_init() {
	if File_login_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_v1_error_reason_proto_rawDesc), len(file_login_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_login_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_login_v1_error_reason_proto_enumTypes,
	}.Build()
	File_login_v1_error_reason_proto = out.File
	file_login_v1_error_reason_proto_goTypes = nil
	file_login_v1_error_reason_proto_depIdxs = nil
}
