// Specify using Protocol Buffers version 3 syntax

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: login/v1/login.proto

// Define the package name for the proto file, used for organization and avoiding naming conflicts

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define login request message
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User account field, field number 1
	// Use validate rules to validate account length, minimum length 5, maximum length 32
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// User password field, field number 2
	// Use validate rules to validate password length, minimum length 8, maximum length 32
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_login_v1_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Define login response message
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication token field, field number 1
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// User information field, field number 2
	User          *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_login_v1_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// Define user information message
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User number field, field number 1
	Num string `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
	// User account field, field number 2
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// User nickname field, field number 3
	NickName string `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// User avatar URL field, field number 4
	Avatar        string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_login_v1_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *UserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_login_v1_login_proto protoreflect.FileDescriptor

const file_login_v1_login_proto_rawDesc = "" +
	"\n" +
	"\x14login/v1/login.proto\x12\x0flayout.login.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"Z\n" +
	"\fLoginRequest\x12#\n" +
	"\aaccount\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x18 R\aaccount\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18 R\bpassword\"Q\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12-\n" +
	"\x04user\x18\x02 \x01(\v2\x19.layout.login.v1.UserInfoR\x04user\"j\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03num\x18\x01 \x01(\tR\x03num\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bnickName\x18\x03 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar2_\n" +
	"\x05Login\x12V\n" +
	"\x05Login\x12\x1d.layout.login.v1.LoginRequest\x1a\x1b.layout.login.v1.LoginReply\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/loginBm\n" +
	"+github.com.go-lynx.lynx-layout.api.login.v1B\fLoginProtoV1P\x01Z.github.com/go-lynx/lynx-layout/api/login/v1;v1b\x06proto3"

var (
	file_login_v1_login_proto_rawDescOnce sync.Once
	file_login_v1_login_proto_rawDescData []byte
)

func file_login_v1_login_proto_rawDescGZIP() []byte {
	file_login_v1_login_proto_rawDescOnce.Do(func() {
		file_login_v1_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_v1_login_proto_rawDesc), len(file_login_v1_login_proto_rawDesc)))
	})
	return file_login_v1_login_proto_rawDescData
}

var file_login_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_login_v1_login_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: layout.login.v1.LoginRequest
	(*LoginReply)(nil),   // 1: layout.login.v1.LoginReply
	(*UserInfo)(nil),     // 2: layout.login.v1.UserInfo
}
var file_login_v1_login_proto_depIdxs = []int32{
	2, // 0: layout.login.v1.LoginReply.user:type_name -> layout.login.v1.UserInfo
	0, // 1: layout.login.v1.Login.Login:input_type -> layout.login.v1.LoginRequest
	1, // 2: layout.login.v1.Login.Login:output_type -> layout.login.v1.LoginReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_login_v1_login_proto_init() }
func file_login_v1_login_proto_init() {
	if File_login_v1_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_v1_login_proto_rawDesc), len(file_login_v1_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_v1_login_proto_goTypes,
		DependencyIndexes: file_login_v1_login_proto_depIdxs,
		MessageInfos:      file_login_v1_login_proto_msgTypes,
	}.Build()
	File_login_v1_login_proto = out.File
	file_login_v1_login_proto_goTypes = nil
	file_login_v1_login_proto_depIdxs = nil
}
