// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary key ID"},
		{Name: "num", Type: field.TypeString, Unique: true, Size: 32, Comment: "User number"},
		{Name: "account", Type: field.TypeString, Size: 32, Comment: "Account", Default: ""},
		{Name: "password", Type: field.TypeString, Size: 100, Comment: "Password", Default: ""},
		{Name: "phone", Type: field.TypeString, Size: 11, Comment: "Phone number", Default: ""},
		{Name: "nickname", Type: field.TypeString, Size: 20, Comment: "Nickname"},
		{Name: "avatar", Type: field.TypeString, Size: 240, Comment: "Avatar", Default: ""},
		{Name: "stats", Type: field.TypeInt32, Comment: "Account status 1:normal;2:banned", Default: 1},
		{Name: "note", Type: field.TypeString, Size: 120, Comment: "Personal introduction", Default: ""},
		{Name: "register_source", Type: field.TypeInt32, Comment: "Registration source 1:web;2:app"},
		{Name: "last_login_at", Type: field.TypeTime, Comment: "Last login time", SchemaType: map[string]string{"mysql": "datetime(3)", "postgres": "timestamptz"}},
		{Name: "created_at", Type: field.TypeTime, Comment: "Created time", SchemaType: map[string]string{"mysql": "datetime(3)", "postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Updated time", SchemaType: map[string]string{"mysql": "datetime(3)", "postgres": "timestamptz"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Comment:    "User table",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
