// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-lynx/lynx-layout/internal/biz"
	"github.com/go-lynx/lynx-layout/internal/data"
	"github.com/go-lynx/lynx-layout/internal/server"
	"github.com/go-lynx/lynx-layout/internal/service"
	"github.com/go-lynx/lynx/app"
	kratos2 "github.com/go-lynx/lynx/app/kratos"
	db "github.com/go-lynx/lynx/plugins/db/pgsql"
	"github.com/go-lynx/lynx/plugins/nosql/redis"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger) (*kratos.App, error) {
	driver := db.GetDriver()
	client := redis.GetRedis()
	dataData, err := data.NewData(driver, client)
	if err != nil {
		return nil, err
	}
	loginRepo := data.NewLoginRepo(dataData)
	loginUseCase := biz.NewLoginUseCase(loginRepo)
	loginService := service.NewLoginService(loginUseCase)
	grpcServer := server.NewGRPCServer(loginService)
	httpServer := server.NewHTTPServer(loginService)
	registrar, _ := app.GetServiceRegistry()
	options := kratos2.ProvideKratosOptions(grpcServer, httpServer, registrar)
	kratosApp, _ := kratos2.NewKratos(options)
	return kratosApp, nil
}
