// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"github.com/go-kratos/kratos/v2/transport"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/go-lynx/lynx"
	"github.com/go-lynx/lynx-layout/internal/biz"
	"github.com/go-lynx/lynx-layout/internal/data"
	"github.com/go-lynx/lynx-layout/internal/server"
	"github.com/go-lynx/lynx-layout/internal/service"
	"github.com/go-lynx/lynx/plugins/nosql/redis"
	"github.com/go-lynx/lynx/plugins/sql/mysql"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger) (*kratos.App, error) {
	driver, err := mysql.GetDriver()
	if err != nil {
		return nil, err
	}
	client := redis.GetRedis()
	dataData, err := data.NewData(driver, client)
	if err != nil {
		return nil, err
	}
	loginRepo := data.NewLoginRepo(dataData)
	loginUseCase := biz.NewLoginUseCase(loginRepo)
	loginService := service.NewLoginService(loginUseCase)
	grpcServer := server.NewGRPCServer(loginService)
	httpServer := server.NewHTTPServer(loginService)
	registrar, err := lynx.GetServiceRegistry()
	if err != nil {
		return nil, err
	}
	app, err := provideKratosApp(grpcServer, httpServer, registrar)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// provideKratosApp creates a kratos app from servers and registry
func provideKratosApp(
	grpcServer *grpc.Server,
	httpServer *http.Server,
	registrar registry.Registrar,
) (*kratos.App, error) {
	var serverList []transport.Server
	if grpcServer != nil {
		serverList = append(serverList, grpcServer)
	}
	if httpServer != nil {
		serverList = append(serverList, httpServer)
	}

	opts := []kratos.Option{kratos.ID(lynx.GetHost()), kratos.Name(lynx.GetName()), kratos.Version(lynx.GetVersion()), kratos.Metadata(map[string]string{
		"host":    lynx.GetHost(),
		"version": lynx.GetVersion(),
	}), kratos.Logger(log.DefaultLogger),
	}

	if registrar != nil {
		opts = append(opts, kratos.Registrar(registrar))
	}

	if len(serverList) > 0 {
		opts = append(opts, kratos.Server(serverList...))
	}

	return kratos.New(opts...), nil
}
